name: plexmediaserver
version: '1.10.1.4602-f54242b6b'
summary: Your media on all your devices.
architectures: [amd64]
description: |
  Plex makes it possible to enjoy all of your media, whether in your living
  room, the car, or on a boat in the South Pacific!

confinement: strict
grade: stable

apps:
  plexmediaserver:
    command: bin/server.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - removable-media
      - home

parts:
  plexmediaserver:
    plugin: dump
    source: https://downloads.plex.tv/plex-media-server/$SNAPCRAFT_PROJECT_VERSION/plexmediaserver_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    install: |
      rm -f etc/init.d/plexmediaserver
      rm -f ../install/etc/init.d/plexmediaserver

  server-configurations:
    plugin: dump
    prime:
      - bin/server.sh
