name: plexmediaserver
version: 1.10.1.4602-f54242b6b
summary: Unofficial snap for the Plex media server for the amd64 architecture
architectures: [amd64]
description: |
  Plex organizes all of your personal media so you can easily
  access and enjoy it. See https://www.plex.tv/

apps:
  plexmediaserver:
    command: bin/server.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - removable-media
      - home

confinement: strict
grade: stable

parts:
  plexmediaserver:
    plugin: dump
    source: https://downloads.plex.tv/plex-media-server/$SNAPCRAFT_PROJECT_VERSION/plexmediaserver_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    install: |
      rm -f etc/init.d/plexmediaserver
      rm -f ../install/etc/init.d/plexmediaserver

  server-configurations:
    plugin: dump
    prime:
      - bin/server.sh
